# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Newstagram' do
 
  use_frameworks!

  pod 'Kingfisher'
  pod 'StatusProvider'
  pod 'MKDropdownMenu'
end
